<div id="TabbedPanels1" class="TabbedPanels">
 <ul class="TabbedPanelsTabGroup">
  <li class="TabbedPanelsTab" tabindex="0">Events / Promotions</li>
 </ul>
 <div class="TabbedPanelsContentGroup">
  <div class="TabbedPanelsContent1">
   <div class="MasterDetail">
<div spry:region="dsEvents" class="MasterDetail">
    <div spry:repeat="dsEvents" class="DetailContainer">
     <p class="newstitle">{Title}</p>
     
     <p class="arrowlink">{Link}</p>
    </div>
   </div>
    
    <br style="clear:both" />
   </div>
   <!--END MASTER DETAIL-->
  </div>
  <!--END TabbedPanelsContent(1) -->
 </div>
</div>
<!--END TabbedPanels1-->
<br class="clearFloat" />


