<div id="header">
   <div id="searchcontainer"> 
     <!-- Google CSE Search Box Begins  -->
    <table border="0" cellspacing="0" cellpadding="0">
     <tr><form action="/searchresults.html" id="cse-search-box">
      <td><img src="/images/bckgrnds/search-txt.gif" width="35" height="17" /></td>
      <td valign="middle"><input type="hidden" name="cx" value="003443676541526465990:g2w6rkcoop8" />
      <input type="hidden" name="cof" value="FORID:11" />
      <input type="hidden" name="ie" value="UTF-8" />
      <input type="text" name="q" size="14" maxlength="30" /></td>
      <td>&nbsp;<input name="sa" type="image" value="Search" src="/images/bckgrnds/go-search.gif" alt="Start Search" width="26" height="21" /></td>
     </form></tr>
    </table>
    
<!-- Google CSE Search Box Ends -->
   </div> 
 </div>