<ul id="MenuBar1" class="MenuBarHorizontal">
    <li><a href="/index.html">HOME</a></li>
    <li><a href="/about/about.html">ABOUT US</a></li>
    <li><a href="/news/events.html">EVENTS / PROMOTIONS</a></li>
    
    <li><a class="MenuBarItemSubmenu" href="#">TRAINING</a>
      <ul>
       <li><a href="/training/index.html">Training</a></li>
	   <li><a href="/training/resources/index.html">Resources</a></li>
	      </ul>
   </li>
   
    <li><a class="MenuBarItemSubmenu" href="#">SOFTWARE SALES</a>
      <ul>
       <li><a href="/software/CAD/index.html">CAD</a></li>
	   <li><a href="/software/CAM/index.html">CAM</a></li>
	   <li><a href="/software/CAE/Femap/index.html">CAE</a></li>
	   <li><a href="/software/PLM/index.html">PLM</a></li>
        <li>
          <a href="/software/FIBERSIM/index.html">FIBERSIM</a>
        </li>
		<li>
          <a href="/software/BCT/index.html">BCT</a>
        </li>
      </ul>
   </li>
        <li><a class="MenuBarItemSubmenu" href="#">SUPPORT</a>
         <ul>
       <li><a href="/support/CAD/index.html">CAD</a></li>
	   <li><a href="/support/CAM/index.html">CAM</a></li>
	   <li><a href="/support/CAE/index.html">CAE</a></li>
	   <li><a href="/support/PLM/index.html">PLM</a></li>
      </ul>
   </li>
	<li><a href="/contact/index.html">CONTACT</a></li>
</ul>
   
<script type="text/javascript">
<!--
var MenuBar1 = new Spry.Widget.MenuBar("MenuBar1", {imgDown:"/SpryAssets/SpryMenuBarDownHover.gif", imgRight:"/SpryAssets/SpryMenuBarRightHover.gif"});
//-->
</script>